"""Add disposed_date column to disposed_item

Revision ID: 848606b42bf5
Revises: ad8e60d64b8f
Create Date: 2025-04-29 15:45:47.593578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848606b42bf5'
down_revision = 'ad8e60d64b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disposed_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disposed_date', sa.Date(), nullable=False))
        batch_op.drop_index('ix_disposed_item_disposal_date')
        batch_op.create_index(batch_op.f('ix_disposed_item_disposed_date'), ['disposed_date'], unique=False)
        batch_op.drop_column('disposal_date')

    with op.batch_alter_table('item_location', schema=None) as batch_op:
        batch_op.create_index('ix_itemlocation_item_quantity', ['item_id', 'quantity'], unique=False)

    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.create_index('ix_movement_date_person', ['movement_date', 'responsible_person'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.drop_index('ix_movement_date_person')

    with op.batch_alter_table('item_location', schema=None) as batch_op:
        batch_op.drop_index('ix_itemlocation_item_quantity')

    with op.batch_alter_table('disposed_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disposal_date', sa.DATE(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_disposed_item_disposed_date'))
        batch_op.create_index('ix_disposed_item_disposal_date', ['disposal_date'], unique=False)
        batch_op.drop_column('disposed_date')

    # ### end Alembic commands ###
