"""Add cascade delete to foreign keys in Movement and DisposedItem

Revision ID: b563b4b6a906
Revises: d31861b51649
Create Date: 2025-08-18 23:44:44.011203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b563b4b6a906'
down_revision = 'd31861b51649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###