"""Remove Disposal model

Revision ID: d31861b51649
Revises: 848606b42bf5
Create Date: 2025-04-30 10:23:30.939818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31861b51649'
down_revision = '848606b42bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_index('ix_movement_movement_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.create_index('ix_movement_movement_date', ['movement_date'], unique=False)
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
